index:
   path: /servicios
   controller: App\Controller\ServicioController::index
   methods: ['GET']

idiomas:
   path: /servicios/{idioma}
   controller: App\Controller\TraduccionController::getByTraducciones
   methods: ['GET']